apiVersion: v1
kind: Service
metadata:
    name: ttrend
    namespace: kfgmartinez-namespace
spec:
    type: NodePort
    selector:
        app: ttrend-label
    ports:
    - nodePort: 30080
      port: 8000
      targetPort: 8000 